### PR TITLE
Allow RedHat family to install

### PR DESCRIPTION
**Pull request by tykeal**
Signed-off-by: Andrew Grimberg <agrimberg@linuxfoundation.org>

### CODE REVIEW

**Comment by bschonec** [comment]
Rather than fork my own, would you be so kind as to accept @tykeal pull request?

**Comment by Flos** [comment]
Thanks for the patch, works fine on CentOS 7.2. 
+1 for a merge

**Comment by dhoppe** [comment]
@tykeal Thanks for your contribution. Please add RedHat to ```metadata.json```, after that I will merge your patch.

**Comment by tykeal** [comment]
@dhoppe would you like me to bump the patch version as well?

**Comment by dhoppe** [comment]
@tykeal Good thinking. That would be great.

**Comment by tykeal** [comment]
There you go :)

**Comment by dhoppe** [comment]
Thanks.

**Comment by tykeal** [comment]
Oh.. hmm... I think I hadn't realized you had released a v 1.0.4 in August! Need to bump up one more minor rev (and probably a CHANGELOG entry) to make this releasable

**Comment by dhoppe** [comment]
Hm. I missed that too.

**Pull request merged**
